# Generated by Django 6.1.1 on 2026-09-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('Turista', 'Turista'), ('Premium', 'Premium')], max_length=20)),
                ('precio_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='Disponible', max_length=20)),
            ],
        ),
    ]
