# Generated by Django 6.1.1 on 2026-10-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_habitacion_options_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='caracteristicas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='equipamiento',
            field=models.TextField(blank=True),
        ),
    ]
